### ISSUE TITLE
drupal/lightning_media[dev-4.x, 4.6.0] require bower-asset/cropper ^2.3 -> could not be found in any version

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/lightning#2]
![image](https://user-images.githubusercontent.com/904576/163971892-7cc54763-e1b1-41d5-a3bf-038d8bc9ca86.png)

Related:

* https://github.com/hiqdev/asset-packagist/issues/146
* https://github.com/dxpr/dxpr_builder/issues/874
* https://ryanszrama.com/blog/04-18-2022/replace-asset-packagist-custom-package-repositories

Fix:

* ~~As lightning_media is not maintained anymore we will clone it and host it on GitHub~~ see comment below
* We will remove asset-packagist.org from lightning_media

**Comment by jjroelofs** [comment]
Correction, it seems like for this issue an exception was made and it has been patched already by phenaproxima:

https://www.drupal.org/project/lightning_media/issues/3275871
https://www.drupal.org/project/lightning_media/issues/3275873

**Comment by SilverFire** [comment]
Asset-packagist is up, sorry for the troubles. You can find an explanation in the original issue: https://github.com/hiqdev/asset-packagist/issues/146#issuecomment-1106742011
